[workspace]
members = [
    "crates/engine",
    "crates/game",
    "crates/thruport_cli",
]
default-members = ["crates/game"]
resolver = "2"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 2
